# conda env create --file environment.yml
# mamba env create --file environment.yml
name: ayatori-gtfs-processor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - rustworkx
  - networkx
  - scipy
  - matplotlib
  - seaborn
  - folium
  - plotly
  - scikit-learn
  - python-dotenv
  - jupyter
  - jupyterlab
  - black
  - pylint
  - invoke
  # Geospatial dependencies (easier with conda)
  - geopandas
  - rtree
  - pyrosm
  - pip:
    - pygtfs
    - geopy
    - pandas-flavor
    - pyjanitor
    - pyprojroot
    - nbdime
